version: '3.8'

services:
  db:
    image: postgres:15
    container_name: teacher_db
    volumes:
      - teacher_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-teacher}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teacher_fastapi
    env_file: .env
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app

volumes:
  teacher_postgres: