version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teacher_fastapi
    ports:
      - "8088:8088"
    environment:
      - ENV=${ENV:-development}
      - DEBUG=${DEBUG:-true}
    volumes:
      - ./:/app